[package]
name = "asn1_codecs_bench"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# HAMPI dependencies
asn1-codecs = "0.7.0"
asn1_codecs_derive = "0.7.0"
asn1rs = "0.3.1"
bitvec = "1"
log = { version = "0.4", features = ["release_max_level_info"] }

# RASN dependencies
rasn = "0.16.5"

[dev-dependencies]
criterion = "0.5.1"

[[bench]]
name = "sample"
harness = false

[[bench]]
name = "simple_types"
harness = false

[profile.release-with-debug]
inherits = "release"
debug = true
